export const ACTIONS = {
  CREATE_LIST: 'CREATE_LIST',
  UPDATE_LIST: 'UPDATE_LIST',
  ADD_TASK: 'ADD_TASK',
  UPDATE_TASK: 'UPDATE_TASK',
  TOGGLE_TASK: 'TOGGLE_TASK',
  DELETE_TASK: 'DELETE_TASK',
  DELETE_LIST: 'DELETE_LIST',
  DELETE_ALL_TASKS: 'DELETE_ALL_TASKS',
};
